In [3]:
import json
import pandas as pd
from pathlib import Path
from pyesgf.search import SearchConnection

In [4]:
required_vars = ["tas", "huss", "pr", "rsds", "va100m", "ua100m", 
                 "va150m", "ua150m", "va200m", "ua200m", "hurs", "mrro", "mrros"]

In [5]:
paths = json.load(open("../paths.json"))
path_data_cordex = Path(paths["path_data_cordex"])

# Availability on ESGF

In [6]:
from pyesgf.search import SearchConnection
import pandas as pd

# ESGF search URL (DKRZ Node)
ESGF_URL = "https://esgf-data.dkrz.de/esg-search"

# Connect to ESGF
conn = SearchConnection(ESGF_URL, distrib=True)

# Define variables of interest
variables_of_interest = ["va100m", "ua100m", "va150m", "ua150m", "va200m", "ua200m", "mrro"]

# Search for EURO-CORDEX EUR-11 datasets
ctx = conn.new_context(
    project="CORDEX",
    domain="EUR-11",
    variable=variables_of_interest,
    facets="*",  # Request all facets
)

print(f"Total Hits: {ctx.hit_count}")

# Initialize list to collect dataset info
dataset_info = []

# Iterate over each dataset result
for result in ctx.search():
    # Extract metadata
    model = result.json.get('driving_model', 'Unknown')[0]
    experiment = result.json.get('experiment', 'Unknown')[0]
    variable = result.json.get('variable', 'Unknown')[0]
    rcm_name = result.json.get('rcm_name', 'Unknown')[0]
    resolution = result.json.get('domain', 'Unknown')[0]
    frequency = result.json.get('time_frequency', 'Unknown')[0]
    institute = result.json.get('institute', 'Unknown')[0]

    local_path = path_data_cordex / experiment / frequency / variable / institute / model / f"{institute}-{rcm_name}"
    
    # Append to list
    dataset_info.append({
        "Variable": variable,
        "Experiment": experiment,
        "Institute": institute,
        "Driving Model": model,
        "RCM": rcm_name,
        "Frequency": frequency,
        "Resolution": resolution,
        "Local_Path": str(local_path),
        "Exists_Locally": local_path.exists()
    })

# Convert to DataFrame
df = pd.DataFrame(dataset_info)

# Display DataFrame
df.head()

Total Hits: 805

,Variable,Experiment,Institute,Driving Model,RCM,Frequency,Resolution,Local_Path,Exists_Locally
0,mrro,historical,MOHC,CNRM-CERFACS-CNRM-CM5,HadREM3-GA7-05,6hr,EUR-11,/net/atmos/data/cordex/EUR-11/historical/6hr/m...,False
1,mrro,historical,MOHC,CNRM-CERFACS-CNRM-CM5,HadREM3-GA7-05,day,EUR-11,/net/atmos/data/cordex/EUR-11/historical/day/m...,True
2,mrro,historical,MOHC,CNRM-CERFACS-CNRM-CM5,HadREM3-GA7-05,mon,EUR-11,/net/atmos/data/cordex/EUR-11/historical/mon/m...,True
3,mrro,historical,MOHC,CNRM-CERFACS-CNRM-CM5,HadREM3-GA7-05,sem,EUR-11,/net/atmos/data/cordex/EUR-11/historical/sem/m...,True
4,mrro,rcp85,MOHC,CNRM-CERFACS-CNRM-CM5,HadREM3-GA7-05,6hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp85/6hr/mrro/M...,False

In [7]:
df[(df["Variable"] == "mrro") & (df["Frequency"] == "day") & (df["Experiment"] == "rcp45") & (df["Institute"].isin(["MOHC", "CNRM"]))]

,Variable,Experiment,Institute,Driving Model,RCM,Frequency,Resolution,Local_Path,Exists_Locally
75,mrro,rcp45,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN53,day,EUR-11,/net/atmos/data/cordex/EUR-11/rcp45/day/mrro/C...,True
89,mrro,rcp45,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN63,day,EUR-11,/net/atmos/data/cordex/EUR-11/rcp45/day/mrro/C...,True

In [8]:
df[(df["Variable"] == "va100m") & (df["Experiment"] == "rcp26")]

,Variable,Experiment,Institute,Driving Model,RCM,Frequency,Resolution,Local_Path,Exists_Locally
130,va100m,rcp26,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN63,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/va100m...,False
136,va100m,rcp26,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN63,1hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/1hr/va100m...,False
242,va100m,rcp26,ICTP,NCC-NorESM1-M,RegCM4-6,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/va100m...,False
245,va100m,rcp26,ICTP,NCC-NorESM1-M,RegCM4-6,day,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/day/va100m...,False
262,va100m,rcp26,ICTP,MPI-M-MPI-ESM-LR,RegCM4-6,day,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/day/va100m...,False
265,va100m,rcp26,ICTP,MPI-M-MPI-ESM-LR,RegCM4-6,mon,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/mon/va100m...,False
268,va100m,rcp26,ICTP,MPI-M-MPI-ESM-LR,RegCM4-6,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/va100m...,False
366,va100m,rcp26,ICTP,NCC-NorESM1-M,RegCM4-6,mon,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/mon/va100m...,False
407,va100m,rcp26,ICTP,MOHC-HadGEM2-ES,RegCM4-6,mon,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/mon/va100m...,False
409,va100m,rcp26,ICTP,MOHC-HadGEM2-ES,RegCM4-6,day,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/day/va100m...,False
415,va100m,rcp26,ICTP,MOHC-HadGEM2-ES,RegCM4-6,6hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/6hr/va100m...,False

In [11]:
df[(df["Variable"] == "mrros") & (df["Frequency"] == "day") & (df["Experiment"] == "rcp85") & (df["Institute"].isin(["MOHC", "CNRM"]))]

Empty DataFrame
Columns: [Variable, Experiment, Institute, Driving Model, RCM, Frequency, Resolution, Local_Path, Exists_Locally]
Index: []

# Availability on IAC Servers

In [53]:
df_on_server = df[df["Exists_Locally"] == True]