In [1]:
import json
import pandas as pd
from pathlib import Path
from pyesgf.search import SearchConnection

In [ ]:
required_vars = ["tas", "hurs", "pr", "ps", "rsds", "va100m", "ua100m",
                 "va150m", "ua150m", "va200m", "ua200m",  "mrro", "sfcWind"]

In [3]:
paths = json.load(open("../../paths_so4.json"))
path_data_cordex = Path(paths["path_data_cordex"])

# Availability on ESGF

In [4]:
from pyesgf.search import SearchConnection
import pandas as pd

# ESGF search URL (DKRZ Node)
ESGF_URL = "https://esgf-data.dkrz.de/esg-search"

# Connect to ESGF
conn = SearchConnection(ESGF_URL, distrib=True)

# Define variables of interest
# variables_of_interest = ["va100m", "ua100m", "va150m", "ua150m", "va200m", "ua200m", "mrro"]

# Search for EURO-CORDEX EUR-11 datasets
ctx = conn.new_context(
    project="CORDEX",
    domain="EUR-11",
    variable=required_vars,
    facets="*",  # Request all facets
)

print(f"Total Hits: {ctx.hit_count}")

# Initialize list to collect dataset info
dataset_info = []

# Iterate over each dataset result
for result in ctx.search():
    # Extract metadata
    model = result.json.get('driving_model', 'Unknown')[0]
    experiment = result.json.get('experiment', 'Unknown')[0]
    variable = result.json.get('variable', 'Unknown')[0]
    rcm_name = result.json.get('rcm_name', 'Unknown')[0]
    resolution = result.json.get('domain', 'Unknown')[0]
    frequency = result.json.get('time_frequency', 'Unknown')[0]
    institute = result.json.get('institute', 'Unknown')[0]

    local_path = path_data_cordex / experiment / frequency / variable / institute / model / f"{institute}-{rcm_name}"

    # Append to list
    dataset_info.append({
        "Variable": variable,
        "Experiment": experiment,
        "Institute": institute,
        "Driving Model": model,
        "RCM": rcm_name,
        "Frequency": frequency,
        "Resolution": resolution,
        "Local_Path": str(local_path),
        "Exists_Locally": local_path.exists()
    })

# Convert to DataFrame
df = pd.DataFrame(dataset_info)

# Display DataFrame
df.head()

Total Hits: 3947

,Variable,Experiment,Institute,Driving Model,RCM,Frequency,Resolution,Local_Path,Exists_Locally
0,pr,historical,MOHC,CNRM-CERFACS-CNRM-CM5,HadREM3-GA7-05,1hr,EUR-11,/net/atmos/data/cordex/EUR-11/historical/1hr/p...,True
1,hurs,historical,MOHC,CNRM-CERFACS-CNRM-CM5,HadREM3-GA7-05,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/historical/3hr/h...,True
2,huss,historical,MOHC,CNRM-CERFACS-CNRM-CM5,HadREM3-GA7-05,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/historical/3hr/h...,True
3,pr,historical,MOHC,CNRM-CERFACS-CNRM-CM5,HadREM3-GA7-05,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/historical/3hr/p...,True
4,rsds,historical,MOHC,CNRM-CERFACS-CNRM-CM5,HadREM3-GA7-05,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/historical/3hr/r...,True

In [8]:
df[(df["Frequency"] == "3hr") & (df["Experiment"] == "rcp26") & (df["Institute"].isin(["CNRM", "MOHC"]))]

,Variable,Experiment,Institute,Driving Model,RCM,Frequency,Resolution,Local_Path,Exists_Locally
175,hurs,rcp26,MOHC,ICHEC-EC-EARTH,HadREM3-GA7-05,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/hurs/M...,True
176,huss,rcp26,MOHC,ICHEC-EC-EARTH,HadREM3-GA7-05,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/huss/M...,True
177,pr,rcp26,MOHC,ICHEC-EC-EARTH,HadREM3-GA7-05,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/pr/MOH...,True
178,rsds,rcp26,MOHC,ICHEC-EC-EARTH,HadREM3-GA7-05,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/rsds/M...,True
179,sfcWind,rcp26,MOHC,ICHEC-EC-EARTH,HadREM3-GA7-05,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/sfcWin...,True
180,tas,rcp26,MOHC,ICHEC-EC-EARTH,HadREM3-GA7-05,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/tas/MO...,True
320,hurs,rcp26,MOHC,MOHC-HadGEM2-ES,HadREM3-GA7-05,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/hurs/M...,True
321,huss,rcp26,MOHC,MOHC-HadGEM2-ES,HadREM3-GA7-05,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/huss/M...,True
322,pr,rcp26,MOHC,MOHC-HadGEM2-ES,HadREM3-GA7-05,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/pr/MOH...,True
323,rsds,rcp26,MOHC,MOHC-HadGEM2-ES,HadREM3-GA7-05,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/rsds/M...,True
324,sfcWind,rcp26,MOHC,MOHC-HadGEM2-ES,HadREM3-GA7-05,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/sfcWin...,True
325,tas,rcp26,MOHC,MOHC-HadGEM2-ES,HadREM3-GA7-05,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/tas/MO...,True
631,sfcWind,rcp26,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN63,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/sfcWin...,True
632,tas,rcp26,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN63,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/tas/CN...,True
637,hurs,rcp26,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN63,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/hurs/C...,True
639,rsds,rcp26,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN63,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/rsds/C...,True
640,huss,rcp26,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN63,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/huss/C...,True
641,pr,rcp26,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN63,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/pr/CNR...,True
872,va100m,rcp26,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN63,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/va100m...,False
873,va150m,rcp26,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN63,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/va150m...,False
874,va200m,rcp26,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN63,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/va200m...,False
885,ua200m,rcp26,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN63,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/ua200m...,False
886,ua100m,rcp26,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN63,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/ua100m...,False
887,ua150m,rcp26,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN63,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp26/3hr/ua150m...,False

In [13]:
df[(df["Variable"] == "va100m") & (df["Experiment"] == "rcp85")]

,Variable,Experiment,Institute,Driving Model,RCM,Frequency,Resolution,Local_Path,Exists_Locally
125,va100m,rcp85,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN63,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp85/3hr/va100m...,False
140,va100m,rcp85,CNRM,CNRM-CERFACS-CNRM-CM5,ALADIN63,1hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp85/1hr/va100m...,False
159,va100m,rcp85,CNRM,NCC-NorESM1-M,ALADIN63,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp85/3hr/va100m...,False
163,va100m,rcp85,CNRM,NCC-NorESM1-M,ALADIN63,1hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp85/1hr/va100m...,False
179,va100m,rcp85,CNRM,MOHC-HadGEM2-ES,ALADIN63,3hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp85/3hr/va100m...,False
182,va100m,rcp85,CNRM,MOHC-HadGEM2-ES,ALADIN63,1hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp85/1hr/va100m...,False
362,va100m,rcp85,CLMcom-ETH,ICHEC-EC-EARTH,COSMO-crCLIM-v1-1,1hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp85/1hr/va100m...,False
366,va100m,rcp85,CLMcom-ETH,ICHEC-EC-EARTH,COSMO-crCLIM-v1-1,1hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp85/1hr/va100m...,False
379,va100m,rcp85,CLMcom-ETH,CNRM-CERFACS-CNRM-CM5,COSMO-crCLIM-v1-1,1hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp85/1hr/va100m...,False
494,va100m,rcp85,CLMcom-ETH,MPI-M-MPI-ESM-LR,COSMO-crCLIM-v1-1,1hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp85/1hr/va100m...,False
498,va100m,rcp85,CLMcom-ETH,MOHC-HadGEM2-ES,COSMO-crCLIM-v1-1,1hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp85/1hr/va100m...,False
513,va100m,rcp85,CLMcom-ETH,MPI-M-MPI-ESM-LR,COSMO-crCLIM-v1-1,1hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp85/1hr/va100m...,False
549,va100m,rcp85,CLMcom-ETH,ICHEC-EC-EARTH,COSMO-crCLIM-v1-1,1hr,EUR-11,/net/atmos/data/cordex/EUR-11/rcp85/1hr/va100m...,False